name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SiphosakheM/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "SiphosakheMathews"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # Do not paste your github token here - this is a placeholder
                                                  # and will pull your github token automatically
          
      - name: Commit and push badge
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./assets/tryhackme-badge.png
          git commit -m "Updated THM profile badge" || echo "No changes to commit"
          git push
